list_of_assets = [
    {
        "list_of_things": 1,
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [0, 1],
        "are_01": True,
        "are_bools": False,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1, 2, 3],
        "are_01": False,
        "are_bools": False,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": True,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1, -2, 3],
        "are_01": False,
        "are_bools": False,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1.0, 2.0, 3.0],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": True,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1.0, -2.0, 3.0],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": "this",
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": {"this": "that"},
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [{"this": "that"}],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": ["this", ["that"]],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [],
        "are_01": True,
        "are_bools": True,
        "are_ints": True,
        "are_nonempty_strs": True,
        "are_positive_floats": True,
        "are_positive_ints": True,
        "are_strs": True,
        "is_list_of_str": True,
    },
    {
        "list_of_things": ["", "this"],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": True,
        "is_list_of_str": True,
    },
    {
        "list_of_things": ["this", "that"],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": True,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": True,
        "is_list_of_str": True,
    },
    # += boolean
    {
        "list_of_things": True,
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [0, 1, True],
        "are_01": True,
        "are_bools": False,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [True],
        "are_01": True,
        "are_bools": True,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": True,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [False],
        "are_01": True,
        "are_bools": True,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [False, True],
        "are_01": True,
        "are_bools": True,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1, 2, 3, True],
        "are_01": False,
        "are_bools": False,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": True,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1, -2, 3, False],
        "are_01": False,
        "are_bools": False,
        "are_ints": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1.0, 2.0, 3.0, False],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1.0, -2.0, 3.0, True],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": {"this": True},
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [{"this": False}],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": ["this", [True]],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": ["", "this", True],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": ["this", "that", False],
        "are_01": False,
        "are_bools": False,
        "are_ints": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "are_strs": False,
        "is_list_of_str": False,
    },
]
