list_of_assets = [
    {
        "list_of_things": 1,
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [0, 1],
        "are_01": True,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1, 2, 3],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": True,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1, -2, 3],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1.0, 2.0, 3.0],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": True,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [1.0, -2.0, 3.0],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": "this",
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": {"this": "that"},
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [{"this": "that"}],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": ["this", ["that"]],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": False,
    },
    {
        "list_of_things": [],
        "are_01": True,
        "are_nonempty_strs": True,
        "are_positive_floats": True,
        "are_positive_ints": True,
        "is_list_of_str": True,
    },
    {
        "list_of_things": ["", "this"],
        "are_01": False,
        "are_nonempty_strs": False,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": True,
    },
    {
        "list_of_things": ["this", "that"],
        "are_01": False,
        "are_nonempty_strs": True,
        "are_positive_floats": False,
        "are_positive_ints": False,
        "is_list_of_str": True,
    },
]
